# NumPy - Copies, Views and Sort 

## Agenda:
1. No Copy
2. View or shallow copy
3. Deep Copy
4. Sort Arrays

In [1]:
import numpy as np

## 1. No Copy
Simple assignments do not make the copy of array object. Instead, it uses the same id() of the original array to access it.

### Example 1:

In [2]:
a = np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [3]:
b = a
print(b)

[0 1 2 3 4 5 6 7 8]


In [4]:
np.shares_memory(a, b)

True

### Example 2: 
Changing the shape of array 'b' as 3 rows and 3 columns

In [5]:
print(b)
print(b.shape)

[0 1 2 3 4 5 6 7 8]
(9,)


In [6]:
b.shape = 3,3
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Conclusion : If we change the shape of array 'b' , the shape of array 'a' will also be changed. 

## 2. View or Shallow Copy
It is a new array object that looks at the same data of the original array.

### Example 3: 

In [8]:
a = np.arange(9)
b = a.view()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]


In [9]:
np.shares_memory(a, b)

True

In [10]:
b.shape = 3,3
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
print(a)

[0 1 2 3 4 5 6 7 8]


Conclusion: If we change the shape of array 'b' , it doesn't affect the shape of array 'a'.

## 3. Deep Copy
It is a complete copy of the array and its data, and doesn’t share with the original array.

### Example 4:

In [12]:
a = np.arange(9)
print(a)
print(id(a))

[0 1 2 3 4 5 6 7 8]
2211222890736


In [13]:
b = a.copy()
print(b)
print(id(b))

[0 1 2 3 4 5 6 7 8]
2211222891936


In [14]:
np.shares_memory(a, b)

False

## Sort Arrays

### Example 5:

In [15]:
# Multi dimensional data set 
a =  np.random.randint(16, size=(3, 3))
print("Input Array is \n", a) 

Input Array is 
 [[12  6  5]
 [11  3  8]
 [ 1  8  2]]


In [16]:
# By default it will sort in row wise 
print("Sorting the array\n",np.sort(a))

Sorting the array
 [[ 5  6 12]
 [ 3  8 11]
 [ 1  2  8]]


In [17]:
# sort along the y axis
arr = np.sort((a), axis=0)
print("Original Array \n",a)
print("Sorting the array\n",arr)

Original Array 
 [[12  6  5]
 [11  3  8]
 [ 1  8  2]]
Sorting the array
 [[ 1  3  2]
 [11  6  5]
 [12  8  8]]


In [18]:
# sort along the x axis
arr = np.sort((a), axis=1)
print("Original Array \n",a)
print("Sorting the array\n",arr)

Original Array 
 [[12  6  5]
 [11  3  8]
 [ 1  8  2]]
Sorting the array
 [[ 5  6 12]
 [ 3  8 11]
 [ 1  2  8]]


In [19]:
# The multi dimension will be converted into 1D array
arr = np.sort((a), axis=None)
print("Original Array \n",a)
print("Sorting the array\n",arr)
print(arr.shape)

Original Array 
 [[12  6  5]
 [11  3  8]
 [ 1  8  2]]
Sorting the array
 [ 1  2  3  5  6  8  8 11 12]
(9,)
