# NumPy - Copies, Views and Sort 

In [1]:
import numpy as np

## 1. No Copy
Simple assignments do not make the copy of array object. Instead, it uses the same id() of the original array to access it.

### Example 1:

In [2]:
a = np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [3]:
b = a
print(b)

[0 1 2 3 4 5 6 7 8]


In [4]:
np.shares_memory(a, b)

True

### Example 2: 
Changing the shape of array 'b' as 3 rows and 3 columns

In [5]:
b.shape = 3,3
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Conclusion : If we change the shape of array 'b' , the shape of array 'a' will also be changed. 

## 2. View or Shallow Copy
It is a new array object that looks at the same data of the original array.

### Example 3: 

In [7]:
a = np.arange(9)
b = a.view()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]


In [8]:
np.shares_memory(a, b)

True

In [9]:
b.shape = 3,3
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
print(a)

[0 1 2 3 4 5 6 7 8]


Conclusion: If we change the shape of array 'b' , it doesn't affect the shape of array 'a'.

## 3. Deep Copy
It is a complete copy of the array and its data, and doesn’t share with the original array.

### Example 4:

In [11]:
a = np.arange(9)
print(a)
print(id(a))

[0 1 2 3 4 5 6 7 8]
1485739994688


In [12]:
b = a.copy()
print(b)
print(id(b))

[0 1 2 3 4 5 6 7 8]
1485740024816


In [13]:
np.shares_memory(a, b)

False

## Sort Arrays

### Example 5:

In [14]:
# Multi dimensional data set
a =  np.random.randint(16, size=(3, 3))
print("Input Array is \n", a)

Input Array is 
 [[15  9  0]
 [ 5 11  4]
 [15  6  5]]


In [15]:
print("Sorting the array\n",np.sort(a))

Sorting the array
 [[ 0  9 15]
 [ 4  5 11]
 [ 5  6 15]]


In [16]:
# sort along the first axis 
arr = np.sort((a), axis=0)
print("Original Array \n",a)
print("Sorting the array\n",arr)

Original Array 
 [[15  9  0]
 [ 5 11  4]
 [15  6  5]]
Sorting the array
 [[ 5  6  0]
 [15  9  4]
 [15 11  5]]


In [17]:
# sort along the last axis 
arr = np.sort((a), axis=0)
print("Original Array \n",a)
print("Sorting the array\n",arr)

Original Array 
 [[15  9  0]
 [ 5 11  4]
 [15  6  5]]
Sorting the array
 [[ 5  6  0]
 [15  9  4]
 [15 11  5]]


In [18]:
arr = np.sort((a), axis=None)
print("Original Array \n",a)
print("Sorting the array\n",arr)

Original Array 
 [[15  9  0]
 [ 5 11  4]
 [15  6  5]]
Sorting the array
 [ 0  4  5  5  6  9 11 15 15]
